# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC/meteo_utils.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gRPC/meteo_utils.proto\x12\x05meteo\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x12\x41irConditionParams\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\"<\n\x13\x41irAnalysisResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\"(\n\x19PollutionAnalysisResponse\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\"\x1f\n\x0b\x41irWellness\x12\x10\n\x08wellness\x18\x01 \x01(\x02\"\x1f\n\x0b\x43o2Wellness\x12\x10\n\x08wellness\x18\x01 \x01(\x02\x32\xbc\x02\n\x10MeteoDataService\x12\x44\n\x10ProcessMeteoData\x12\x1a.meteo.AirAnalysisResponse\x1a\x12.meteo.AirWellness\"\x00\x12N\n\x14ProcessPollutionData\x12 .meteo.PollutionAnalysisResponse\x1a\x12.meteo.Co2Wellness\"\x00\x12\x42\n\nAnalyzeAir\x12\x16.google.protobuf.Empty\x1a\x1a.meteo.AirAnalysisResponse\"\x00\x12N\n\x10\x41nalyzePollution\x12\x16.google.protobuf.Empty\x1a .meteo.PollutionAnalysisResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.meteo_utils_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRCONDITIONPARAMS._serialized_start=62
  _AIRCONDITIONPARAMS._serialized_end=134
  _AIRANALYSISRESPONSE._serialized_start=136
  _AIRANALYSISRESPONSE._serialized_end=196
  _POLLUTIONANALYSISRESPONSE._serialized_start=198
  _POLLUTIONANALYSISRESPONSE._serialized_end=238
  _AIRWELLNESS._serialized_start=240
  _AIRWELLNESS._serialized_end=271
  _CO2WELLNESS._serialized_start=273
  _CO2WELLNESS._serialized_end=304
  _METEODATASERVICE._serialized_start=307
  _METEODATASERVICE._serialized_end=623
# @@protoc_insertion_point(module_scope)
