# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC/PROTO/proxy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gRPC/PROTO/proxy.proto\x1a\x1bgoogle/protobuf/empty.proto\"J\n\x13\x41irAnalysisResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x0c\n\x04time\x18\x03 \x01(\x02\"6\n\x19PollutionAnalysisResponse\x12\x0b\n\x03\x63o2\x18\x01 \x01(\x02\x12\x0c\n\x04time\x18\x02 \x01(\x02\"\xa5\x01\n\x0fWellnessResults\x12\x13\n\x0bwellnessCo2\x18\x01 \x01(\x02\x12\x15\n\rwellnessMeteo\x18\x02 \x01(\x02\x12\x0e\n\x06\x61vgCo2\x18\x03 \x01(\x02\x12\x10\n\x08\x61vgMeteo\x18\x04 \x01(\x02\x12\x0f\n\x07\x64\x65svCo2\x18\x05 \x01(\x02\x12\x11\n\tdesvMeteo\x18\x06 \x01(\x02\x12\x0e\n\x06regCo2\x18\x07 \x01(\x02\x12\x10\n\x08regMeteo\x18\x08 \x01(\x02\x32\xd4\x01\n\rProxyServicer\x12\x44\n\x0cGetPollution\x12\x1a.PollutionAnalysisResponse\x1a\x16.google.protobuf.Empty\"\x00\x12:\n\x08GetMeteo\x12\x14.AirAnalysisResponse\x1a\x16.google.protobuf.Empty\"\x00\x12\x41\n\x13SendWellnessResults\x12\x16.google.protobuf.Empty\x1a\x10.WellnessResults\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.PROTO.proxy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AIRANALYSISRESPONSE._serialized_start=55
  _AIRANALYSISRESPONSE._serialized_end=129
  _POLLUTIONANALYSISRESPONSE._serialized_start=131
  _POLLUTIONANALYSISRESPONSE._serialized_end=185
  _WELLNESSRESULTS._serialized_start=188
  _WELLNESSRESULTS._serialized_end=353
  _PROXYSERVICER._serialized_start=356
  _PROXYSERVICER._serialized_end=568
# @@protoc_insertion_point(module_scope)
