# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gRPC.PROTO import proxy_pb2 as gRPC_dot_PROTO_dot_proxy__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ProxyServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPollution = channel.unary_unary(
                '/ProxyServicer/GetPollution',
                request_serializer=gRPC_dot_PROTO_dot_proxy__pb2.PollutionAnalysisResponse.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetMeteo = channel.unary_unary(
                '/ProxyServicer/GetMeteo',
                request_serializer=gRPC_dot_PROTO_dot_proxy__pb2.AirAnalysisResponse.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendWellnessResults = channel.unary_unary(
                '/ProxyServicer/SendWellnessResults',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gRPC_dot_PROTO_dot_proxy__pb2.WellnessResults.FromString,
                )


class ProxyServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPollution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMeteo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWellnessResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPollution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPollution,
                    request_deserializer=gRPC_dot_PROTO_dot_proxy__pb2.PollutionAnalysisResponse.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMeteo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMeteo,
                    request_deserializer=gRPC_dot_PROTO_dot_proxy__pb2.AirAnalysisResponse.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendWellnessResults': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWellnessResults,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gRPC_dot_PROTO_dot_proxy__pb2.WellnessResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProxyServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPollution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProxyServicer/GetPollution',
            gRPC_dot_PROTO_dot_proxy__pb2.PollutionAnalysisResponse.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMeteo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProxyServicer/GetMeteo',
            gRPC_dot_PROTO_dot_proxy__pb2.AirAnalysisResponse.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendWellnessResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProxyServicer/SendWellnessResults',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gRPC_dot_PROTO_dot_proxy__pb2.WellnessResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
