# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gRPC.PROTO import terminal_pb2 as gRPC_dot_PROTO_dot_terminal__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TerminalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWellnessResults = channel.unary_unary(
                '/TerminalService/SendWellnessResults',
                request_serializer=gRPC_dot_PROTO_dot_terminal__pb2.WellnessResults.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class TerminalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendWellnessResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWellnessResults': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWellnessResults,
                    request_deserializer=gRPC_dot_PROTO_dot_terminal__pb2.WellnessResults.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendWellnessResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TerminalService/SendWellnessResults',
            gRPC_dot_PROTO_dot_terminal__pb2.WellnessResults.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
